### ISSUE TITLE
windows only it seems, right? 

### ISSUE THREAD

**Issue by anwac** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#12]
add_tags.py gets included, but that one says 

# requires pywin32 (See requirements.txt. Supports Windows only obviously)
in line3. So, this is Windows only, correct?

In Linux web-ui launches with the usual message

**Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory.**

probably a reaction to the failed import of add_tags.py

ubuntu 22.04

regardless if installed via UI extensions or git pull.

**Comment by tsngo** [comment]
I added additional logging for this error: `Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory`. See if it provides anymore insights. pywin32 for windows tags, but it shouldn't cause any problems if you don't try to use windows tags.

**Comment by h-sahin** [comment]
I'm also not on Windows and get the same error. Here's the full traceback in case you're still interested in fixing this:

```
ERROR:root:Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
Traceback (most recent call last):
  File "/data/apps/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py", line 26, in <module>
    from tools.add_tags import tag_files
  File "/data/apps/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/tools/add_tags.py", line 6, in <module>
    import pythoncom
ModuleNotFoundError: No module named 'pythoncom'
```

I get this error when loading the WebUI which causes the extension to not show up at all. So not caused by trying to use Windows tags. Looks like pythoncom is part of pywin32 which is Windows only and gets loaded on start up even if you're not using any Windows features.

**Comment by adamflorizone** [comment]
+1 pythoncom windows only

Running Linux:
```
ERROR:root:Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
Traceback (most recent call last):
  File "/stable-diffusion-webui/extensions-builtin/stable-diffusion-webui-aesthetic-image-scorer.git/scripts/image_scorer.py", line 26, in <module>
    from tools.add_tags import tag_files
  File "/stable-diffusion-webui/extensions-builtin/stable-diffusion-webui-aesthetic-image-scorer.git/tools/add_tags.py", line 6, in <module>
    import pythoncom
```
https://pypi.org/project/pywin32/

Per Readme:
```
After restarting the ui, see settings for options
```

I did not see anything added to UI under settings or any new tabs.

This project, at least, needs a warning that it is Windows only.
