### ISSUE TITLE
Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory

### ISSUE THREAD

**Issue by visjble** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#14]
I did copy the add_tags.py in the right folder to no avail

**Comment by rpillala** [comment]
My tools directory already contains add_tags.py and I'm getting the same error at launch, in Windows 10

**Comment by rodrix3855** [comment]
Same issue

**Comment by rodrix3855** [comment]
Can you specify which is the "right folder"?  add_tags.py is on tools by default when you git clone

**Comment by visjble** [comment]
The default folder

**Comment by rodrix3855** [comment]
Then the file is already there when doing pull. Can you specify the full path?

**Comment by jasoncharles** [comment]
I have the same error running on windows. The full path for the file add_tags.py on my computer is:- 

C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\tools\add_tags.py

**Comment by Rodrix33333** [comment]
I confirm I have the same path. Not working

**Comment by ChinatsuHS** [comment]
works only when you run as administrator

-open powershell as administrator
-cd to your webui folder
- `./webui-user.bat`

will install pywin32 just fine and load the extension without errors

**Comment by tsngo** [comment]
I personally don't run as administrator and it works fine. This is a weird one. This error seems to indicate it's unable to load tools\add_tags.py for some reason. Although it does this right after installing pywin32, shouldn't have anything to do with that library. I changed this error logging so that it should output additional info. Hopefully someone can try it and see if it provides more insight into the cause.

**Comment by schoenid** [comment]
I've got this message on my linux machine:
```
ERROR:root:Aesthetic Image Scorer: Unable to load Windows tagging script from tools directory
Traceback (most recent call last):
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py", line 26, in <module>
    from tools.add_tags import tag_files
  File "/home/sd/Tech/Linux/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/tools/add_tags.py", line 6, in <module>
    import pythoncom
ModuleNotFoundError: No module named 'pythoncom'
```
This is because "pythoncom" is part of pywin32.

If I try to install it, it gives me an error:
```
$ pip install pywin32
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

After short toughts, I've got the idea, that this is for Windows and it is not compatible with Linux.

My system:

> Operating System: Ubuntu Studio 22.04
> KDE Plasma Version: 5.24.7
> KDE Frameworks Version: 5.92.0
> Qt Version: 5.15.3
> Kernel Version: 6.2.0-1014-lowlatency (64-bit)
> Graphics Platform: X11
> Processors: 16 × 13th Gen Intel® Core™ i7-13700K
> Memory: 62.5 GiB of RAM
> Graphics Processor: NVIDIA GeForce RTX 3060/PCIe/SSE2
