### ISSUE TITLE
Problem with saving sampler

### ISSUE THREAD

**Issue by MicZet** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#15]
Looks like there is problem with saving sampler. By default it isn't saved, if you set it via options - it doesn't save either.
Looks like it cannot get sampler_index somehow...

``
Error executing callback image_saved_callback for /SDwebui/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py
Traceback (most recent call last):
  File "/SDwebui/stable-diffusion-webui/modules/script_callbacks.py", line 129, in image_saved_callback
    c.callback(params)
  File "/SDwebui/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py", line 250, in on_image_saved
    applied = ais_group.apply(opts, params)
  File "/SDwebui/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py", line 173, in apply
    choice_values.update({choice: processor(params)})
  File "/SDwebui/stable-diffusion-webui/extensions/stable-diffusion-webui-aesthetic-image-scorer/scripts/image_scorer.py", line 108, in <lambda>
    "sampler": lambda params: sd_samplers.samplers[params.p.sampler_index].name if params.p is not None and params.p.sampler else None,
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_index'
``

Tested with latest auto1111 version and latest version of this script

**Comment by MicZet** [comment]
nevermind - it was bug on auto1111 in fact (with img2img)
