### ISSUE TITLE
Not work in stable diffusion web-ui lastest version[sampler_index]

### ISSUE THREAD

**Issue by jees5555** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#16]
throw  'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_index' Exception

beacuse object StableDiffusionProcessingTxt2Img field sampler_index is be deleted.
I tried t change image_scorer.py 
"sampler": sd_samplers.samplers[p.sampler_index].name, TO "sampler": p.sampler_name,
then it works.
And  self.choice_processors need to be fix too, because it has sd_samplers.samplers[p.sampler_index].name

**Comment by Harvester62** [comment]
I can confirm the same issue here on SD Web UI (Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b) on Windows 10 Pro, Here follows the error message displayed in the console:

Error executing callback image_saved_callback for C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 129, in image_saved_callback
    c.callback(params)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 250, in on_image_saved
    applied = ais_group.apply(opts, params)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 173, in apply
    choice_values.update({choice: processor(params)})
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 108, in <lambda>
    "sampler": lambda params: sd_samplers.samplers[params.p.sampler_index].name if params.p is not None and params.p.sampler else None,
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'sampler_index'

These are the arguments set in the webui-user.bat file: --xformers --opt-split-attention --disable-safe-unpickle --api --deepdanbooru --allow-code --administrator --medvram --ckptfix --cors-allow-origins http://localhost:5173

The above error message is displayed with either the txt2img and img2img generation.

**Comment by Harvester62** [comment]
Just for completeness of information, here follow the error message when using txt2img on SD Web UI (Commit hash: 44c46f0ed395967cd3830dd481a2db759fda5b3b):

Error executing callback image_saved_callback for C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\modules\script_callbacks.py", line 129, in image_saved_callback
    c.callback(params)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 250, in on_image_saved
    applied = ais_group.apply(opts, params)
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 173, in apply
    choice_values.update({choice: processor(params)})
  File "C:\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 108, in <lambda>
    "sampler": lambda params: sd_samplers.samplers[params.p.sampler_index].name if params.p is not None and params.p.sampler else None,
AttributeError: 'StableDiffusionProcessingTxt2Img' object has no attribute 'sampler_index'

**Comment by jees5555** [comment]
temporary solution:
change stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py
97:
[before]"sampler": sd_samplers.samplers[p.sampler_index].name,
[after]"sampler": p.sampler_name,
108:
[before]"sampler": lambda params: sd_samplers.samplers[params.p.sampler_index].name if params.p is not None and params.p.sampler else None,
[after]"sampler": lambda params: params.p.sampler_name if params.p is not None and params.p.sampler else None,

replase all <sd_samplers.samplers[params.p.sampler_index].name> to <p.sampler_name> ,samplers name can get directly.

**Comment by tsngo** [comment]
this should now be fixed
