### ISSUE TITLE
Getting: ERROR:root:Aesthetic Image Scorer: Unable to write tag or category

### ISSUE THREAD

**Issue by jockisen** [tsngo/stable-diffusion-webui-aesthetic-image-scorer#23]
```ERROR:root:Aesthetic Image Scorer: Unable to write tag or category for E:\AI\stable-diffusion-webui\outputs\txt2img-images\cat 2023-03-21\00001-2298721297.png
Traceback (most recent call last):
  File "E:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\tools\add_tags.py", line 68, in tag_files
    ps = set_property(file=file, property="System.Category", values=categories,
  File "E:\AI\stable-diffusion-webui\extensions\stable-diffusion-webui-aesthetic-image-scorer\tools\add_tags.py", line 51, in set_property
    ps.SetValue(pk, newValue)
pywintypes.com_error: (-2003292351, 'Bitmapp-codecen stöder inte bitmappsegenskapen.', None, None)```

**Comment by jockisen** [comment]
Can you please help with this? The extension isn't working. @tsngo

**Comment by jockisen** [comment]
doesn't work with jpeg's either:

```Error executing callback before_image_saved_callback for E:\AI\test\stable-diffusion-webui-master\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py
Traceback (most recent call last):
  File "E:\AI\test\stable-diffusion-webui-master\modules\script_callbacks.py", line 151, in before_image_saved_callback
    c.callback(params)
  File "E:\AI\test\stable-diffusion-webui-master\extensions\stable-diffusion-webui-aesthetic-image-scorer\scripts\image_scorer.py", line 243, in on_before_image_saved
    if len(params.pnginfo["parameters"]) > 0:
KeyError: 'parameters'

ERROR:root:Aesthetic Image Scorer: Unable to write tag or category for C:\Users\joach\Downloads\gjört\sdf\Mona-Lisa-0000.png
Traceback (most recent call last):
  File "E:\AI\test\stable-diffusion-webui-master\extensions\stable-diffusion-webui-aesthetic-image-scorer\tools\add_tags.py", line 66, in tag_files
    ps = set_property(file=file, property="System.Keywords", values=tags,
  File "E:\AI\test\stable-diffusion-webui-master\extensions\stable-diffusion-webui-aesthetic-image-scorer\tools\add_tags.py", line 51, in set_property
    ps.SetValue(pk, newValue)
pywintypes.com_error: (-2003292351, 'Bitmapp-codecen stöder inte bitmappsegenskapen.', None, None)```

**Comment by jockisen** [comment]
hello?

**Comment by madwurmz** [comment]
I got the same error tried fixing it but never got it working.
if it would work it could be revolutionary, make all images above 6 post online, delete all images below 5.. too bad!
